---
#tag::datasource[]
datasources:
  #h2:
  #  url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
  #  username: ${JDBC_USER:sa}
  #  password: ${JDBC_PASSWORD:""}
  #  driverClassName: ${JDBC_DRIVER:org.h2.Driver}
  default:
    url: ${JDBC_URL:`jdbc:oracle:thin:@...`}
    username: ${JDBC_USER:demo}
    password: ${ATP_XXX_DEMO_PW:} # ATP_XXX_DEMO_PW は OCI Secret の名前 - 自動的に置換される
    driverClassName: ${JDBC_DRIVER:oracle.jdbc.OracleDriver}
#end::datasource[]
---
#tag::jpa[]
jpa:
  default:
    properties:
      hibernate:
        #hbm2ddl:
        #  auto: update
        show_sql: true
#end::jpa[]
