CREATE TABLE COUNTRY_GRAAL (COUNTRY_ID NUMBER(10) NOT NULL, COUNTRY_NAME VARCHAR2(255) NULL, PRIMARY KEY (COUNTRY_ID))
INSERT INTO COUNTRY_GRAAL VALUES (1, 'USA')
INSERT INTO COUNTRY_GRAAL VALUES (81, 'Japan')